### ISSUE TITLE
is this published to npm?

### ISSUE THREAD

**Issue by noopkat** [jacobrosenthal/usbtinyisp#1]
Hi!

Thanks for authoring this, I'm wondering if you're planning on publishing this to npm?
I think I have a use for this lib soonish, and would love to import it into my project as an npm dep 😊

Thanks!

**Comment by jacobrosenthal** [comment]
Oh. Hi @noopkat! hrm. I guess not? I THINK I needed https://github.com/nonolith/node-usb/issues/69 for Chrome stuff, and didnt get it so just let it sit. Ill MIT it and post it.

**Comment by jacobrosenthal** [comment]
Woop woop. https://www.npmjs.com/package/usbtinyisp

I still have this hardware and am interested in this so let me know if you want to get a collabo going on.

**Comment by noopkat** [comment]
oh nice, thank you! I'll be using this outside of the browser, so I should be good to go?
It'll be a little while until the use of this comes up (in the next month though I expect), mind if I hit you up again then?

✨

**Comment by jacobrosenthal** [comment]
I think it should be good in node. Let me know and I can poke at it again.
